version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
  commands:
    - echo "DOCKER_REGISTRY_URL: $DOCKER_REGISTRY_URL"
    - echo "DOCKER_REGISTRY_USERNAME: $DOCKER_REGISTRY_USERNAME"
    - echo "DOCKER_REGISTRY_PASSWORD: $DOCKER_REGISTRY_PASSWORD"

  build:
  commands:
    - echo "Running tests..."
    - cd day-13/simple-python-app/
    - echo "Building Docker image..."
    - echo $DOCKER_REGISTRY_PASSWORD | docker login -u "$(echo $DOCKER_REGISTRY_USERNAME | tr '[:upper:]' '[:lower:]')" --password-stdin "$(echo $DOCKER_REGISTRY_URL | tr '[:upper:]' '[:lower:]')"
    - docker build -t "$(echo $DOCKER_REGISTRY_URL | tr '[:upper:]' '[:lower:]')/$(echo $DOCKER_REGISTRY_USERNAME | tr '[:upper:]' '[:lower:]')/simple-python-flask-app:latest" .
    - docker push "$(echo $DOCKER_REGISTRY_URL | tr '[:upper:]' '[:lower:]')/$(echo $DOCKER_REGISTRY_USERNAME | tr '[:upper:]' '[:lower:]')/simple-python-flask-app:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app

