version: 0.2
env:
  parameter-store:
    DOCKER_CREDENTIALS_USERNAME: /myapp/docker-credentials/username
    DOCKER_CREDENTIALS_PASSWORD: /myapp/docker-credentials/password
    DOCKER_CREDENTIALS_URL: /myapp/docker-credentials/url

phases:
  install:
    runtime-versions:
      python: 3.12

  pre_build:
    commands:
      - echo "Converting environment variables to lowercase..."
      - export LOWERCASE_CREDENTIALS_URL=$(echo $DOCKER_CREDENTIALS_URL | tr '[:upper:]' '[:lower:]')
      - export LOWERCASE_CREDENTIALS_USERNAME=$(echo $DOCKER_CREDENTIALS_USERNAME | tr '[:upper:]' '[:lower:]')
      - echo "LOWERCASE_CREDENTIALS_URL: $LOWERCASE_CREDENTIALS_URL"
      - echo "LOWERCASE_CREDENTIALS_USERNAME: $LOWERCASE_CREDENTIALS_USERNAME"

  build:
    commands:
      - echo "Building Docker Image..."
      - echo $DOCKER_CREDENTIALS_PASSWORD | docker login -u "$LOWERCASE_CREDENTIALS_USERNAME" --password-stdin "$LOWERCASE_CREDENTIALS_URL"
      - docker build -t "$LOWERCASE_CREDENTIALS_URL/$LOWERCASE_CREDENTIALS_USERNAME/simple-python-flash-app:latest" .
      - docker push "$LOWERCASE_CREDENTIALS_URL/$LOWERCASE_CREDENTIALS_USERNAME/simple-python-flash-app:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app

